apiVersion: v1
kind: Service
metadata:
  name: wordpress-mongo
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
    tier: mongo
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mongo
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mongo
    spec:
      containers:
      - image: kenrward/mongotest:1.0.3
        name: mongo
        resources:
          limits:
            memory: "500Mi"
            cpu: "200m"
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /var/lib/mongo
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
      